FROM quay.io/centos/centos:stream9

RUN dnf install -y httpd && dnf clean all

WORKDIR /var/www/html/

RUN rm -rf * && \
    echo "<center><h1>This is Manoj Gurjar<h1><center>" > index.html && \
    mkdir -p /run/httpd

EXPOSE 80

CMD ["/usr/sbin/httpd", "-DFOREGROUND"]

