FROM quay.io/centos/centos:stream9

RUN dnf install -y httpd && dnf clean all

WORKDIR /var/www/html/

RUN rm -rf * && \
    echo "This is Manoj Gurjar" > index.html && \
    mkdir -p /run/httpd

EXPOSE 80

HEALTHCHECK --interval=30s --timeout=10s \
CMD curl -f http://localhost || exit 1

CMD ["/usr/sbin/httpd", "-DFOREGROUND"]

