FROM quay.io/centos/centos:stream9

RUN yum install -y httpd git unzip

WORKDIR /var/www/html/

RUN rm -rf /var/www/html/*

RUN wget https://www.toocss.com/free-responsive-html-css-templates/

EXPOSE 80

CMD ["/usr/sbin/httpd", "-DFOREGROUND"]
